import { createActions } from 'redux-actions';

export const LOGIN_EMAIL = 'LOGIN_EMAIL';
export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const INIT_SIGNUP = 'INIT_SIGNUP';
export const SIGNUP_EMAIL = 'SIGNUP_EMAIL';
export const SIGNUP_FACEBOOK = 'SIGNUP_FACEBOOK';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const CHECK_REDIRECT = 'CHECK_REDIRECT';
export const CHECK_REDIRECT_END = 'CHECK_REDIRECT_END';
export const INIT_PASSWORD_RESET = 'INIT_PASSWORD_RESET';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED';
export const INIT_UNSUBSCRIBE = 'INIT_UNSUBSCRIBE';
export const UNSUBSCRIBE = 'UNSUBSCRIBE';
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS';
export const UNSUBSCRIBE_FAILED = 'UNSUBSCRIBE_FAILED';

export const CHECK_LOGIN = 'CHECK_LOGIN';
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';
export const CHECK_LOGIN_FAILED = 'CHECK_LOGIN_FAILED';
export const CHECK_LOGIN_FINISHED = 'CHECK_LOGIN_FINISHED';

export const SET_USER = 'SET_USER';

export const FETCH_HAS_REQUESTED = 'FETCH_HAS_REQUESTED';
export const FETCH_HAS_REQUESTED_SUCCESS = 'FETCH_HAS_REQUESTED_SUCCESS';

const authActions = createActions(
  LOGIN_EMAIL,
  LOGIN_FACEBOOK,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  CHECK_LOGIN,
  CHECK_LOGIN_SUCCESS,
  CHECK_LOGIN_FAILED,
  CHECK_LOGIN_FINISHED,
  INIT_SIGNUP,
  SIGNUP_EMAIL,
  SIGNUP_FACEBOOK,
  SIGNUP_SUCCESS,
  SIGNUP_FAILED,
  INIT_PASSWORD_RESET,
  PASSWORD_RESET,
  PASSWORD_RESET_SUCCESS,
  PASSWORD_RESET_FAILED,
  SET_USER,
  INIT_UNSUBSCRIBE,
  UNSUBSCRIBE,
  UNSUBSCRIBE_SUCCESS,
  UNSUBSCRIBE_FAILED,
  CHECK_REDIRECT,
  CHECK_REDIRECT_END,
  FETCH_HAS_REQUESTED,
  FETCH_HAS_REQUESTED_SUCCESS,
);

export default authActions;
