// flow-typed signature: de61bef6cb1bf04e0e69813e97666a02
// flow-typed version: <<STUB>>/storybook-router_v0.3.3/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-router/dist/react' {
  declare module.exports: any;
}

declare module 'storybook-router/dist/StoryRouter' {
  declare module.exports: any;
}

declare module 'storybook-router/dist/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-router/dist/react.js' {
  declare module.exports: $Exports<'storybook-router/dist/react'>;
}
declare module 'storybook-router/dist/StoryRouter.js' {
  declare module.exports: $Exports<'storybook-router/dist/StoryRouter'>;
}
declare module 'storybook-router/dist/vue.js' {
  declare module.exports: $Exports<'storybook-router/dist/vue'>;
}
