// flow-typed signature: dee4365e8f29729e20759c7b9c18e17e
// flow-typed version: <<STUB>>/decode-uri-component_v^0.2.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'decode-uri-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'decode-uri-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'decode-uri-component/index' {
  declare module.exports: $Exports<'decode-uri-component'>;
}
declare module 'decode-uri-component/index.js' {
  declare module.exports: $Exports<'decode-uri-component'>;
}
