// flow-typed signature: 68f30e6c25824212592e4cb9fbf77fc2
// flow-typed version: <<STUB>>/keen-tracking_v^4.4.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keen-tracking'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keen-tracking' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keen-tracking/dist/keen-loader.min' {
  declare module.exports: any;
}

declare module 'keen-tracking/dist/keen-tracking' {
  declare module.exports: any;
}

declare module 'keen-tracking/dist/keen-tracking.min' {
  declare module.exports: any;
}

declare module 'keen-tracking/dist/node/keen-tracking' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/browser-auto-tracking' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/browser' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/config-default' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/defer-events' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/extend-events' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/helpers/getBrowserProfile' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/helpers/getDatetimeIndex' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/helpers/getDomainName' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/helpers/getDomNodePath' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/helpers/getDomNodeProfile' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/helpers/getScreenProfile' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/helpers/getScrollState' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/helpers/getUniqueId' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/helpers/getWindowProfile' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/index' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/record-events-browser' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/record-events-server' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/server' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/cache-browser' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/cache-node' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/cookie' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/deepExtend' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/fetchRetry' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/listener' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/md5' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/nodeRequestRetry' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/optOut' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/queue' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/serializeForm' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/timer' {
  declare module.exports: any;
}

declare module 'keen-tracking/lib/utils/unique' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keen-tracking/dist/keen-loader.min.js' {
  declare module.exports: $Exports<'keen-tracking/dist/keen-loader.min'>;
}
declare module 'keen-tracking/dist/keen-tracking.js' {
  declare module.exports: $Exports<'keen-tracking/dist/keen-tracking'>;
}
declare module 'keen-tracking/dist/keen-tracking.min.js' {
  declare module.exports: $Exports<'keen-tracking/dist/keen-tracking.min'>;
}
declare module 'keen-tracking/dist/node/keen-tracking.js' {
  declare module.exports: $Exports<'keen-tracking/dist/node/keen-tracking'>;
}
declare module 'keen-tracking/lib/browser-auto-tracking.js' {
  declare module.exports: $Exports<'keen-tracking/lib/browser-auto-tracking'>;
}
declare module 'keen-tracking/lib/browser.js' {
  declare module.exports: $Exports<'keen-tracking/lib/browser'>;
}
declare module 'keen-tracking/lib/config-default.js' {
  declare module.exports: $Exports<'keen-tracking/lib/config-default'>;
}
declare module 'keen-tracking/lib/defer-events.js' {
  declare module.exports: $Exports<'keen-tracking/lib/defer-events'>;
}
declare module 'keen-tracking/lib/extend-events.js' {
  declare module.exports: $Exports<'keen-tracking/lib/extend-events'>;
}
declare module 'keen-tracking/lib/helpers/getBrowserProfile.js' {
  declare module.exports: $Exports<'keen-tracking/lib/helpers/getBrowserProfile'>;
}
declare module 'keen-tracking/lib/helpers/getDatetimeIndex.js' {
  declare module.exports: $Exports<'keen-tracking/lib/helpers/getDatetimeIndex'>;
}
declare module 'keen-tracking/lib/helpers/getDomainName.js' {
  declare module.exports: $Exports<'keen-tracking/lib/helpers/getDomainName'>;
}
declare module 'keen-tracking/lib/helpers/getDomNodePath.js' {
  declare module.exports: $Exports<'keen-tracking/lib/helpers/getDomNodePath'>;
}
declare module 'keen-tracking/lib/helpers/getDomNodeProfile.js' {
  declare module.exports: $Exports<'keen-tracking/lib/helpers/getDomNodeProfile'>;
}
declare module 'keen-tracking/lib/helpers/getScreenProfile.js' {
  declare module.exports: $Exports<'keen-tracking/lib/helpers/getScreenProfile'>;
}
declare module 'keen-tracking/lib/helpers/getScrollState.js' {
  declare module.exports: $Exports<'keen-tracking/lib/helpers/getScrollState'>;
}
declare module 'keen-tracking/lib/helpers/getUniqueId.js' {
  declare module.exports: $Exports<'keen-tracking/lib/helpers/getUniqueId'>;
}
declare module 'keen-tracking/lib/helpers/getWindowProfile.js' {
  declare module.exports: $Exports<'keen-tracking/lib/helpers/getWindowProfile'>;
}
declare module 'keen-tracking/lib/index.js' {
  declare module.exports: $Exports<'keen-tracking/lib/index'>;
}
declare module 'keen-tracking/lib/record-events-browser.js' {
  declare module.exports: $Exports<'keen-tracking/lib/record-events-browser'>;
}
declare module 'keen-tracking/lib/record-events-server.js' {
  declare module.exports: $Exports<'keen-tracking/lib/record-events-server'>;
}
declare module 'keen-tracking/lib/server.js' {
  declare module.exports: $Exports<'keen-tracking/lib/server'>;
}
declare module 'keen-tracking/lib/utils/cache-browser.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/cache-browser'>;
}
declare module 'keen-tracking/lib/utils/cache-node.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/cache-node'>;
}
declare module 'keen-tracking/lib/utils/cookie.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/cookie'>;
}
declare module 'keen-tracking/lib/utils/deepExtend.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/deepExtend'>;
}
declare module 'keen-tracking/lib/utils/fetchRetry.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/fetchRetry'>;
}
declare module 'keen-tracking/lib/utils/listener.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/listener'>;
}
declare module 'keen-tracking/lib/utils/md5.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/md5'>;
}
declare module 'keen-tracking/lib/utils/nodeRequestRetry.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/nodeRequestRetry'>;
}
declare module 'keen-tracking/lib/utils/optOut.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/optOut'>;
}
declare module 'keen-tracking/lib/utils/queue.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/queue'>;
}
declare module 'keen-tracking/lib/utils/serializeForm.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/serializeForm'>;
}
declare module 'keen-tracking/lib/utils/timer.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/timer'>;
}
declare module 'keen-tracking/lib/utils/unique.js' {
  declare module.exports: $Exports<'keen-tracking/lib/utils/unique'>;
}
