// flow-typed signature: f78e7a20cc5adfcd352dd05229ac1d92
// flow-typed version: <<STUB>>/react-image-gallery_v^0.8.11/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-gallery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-gallery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-gallery/build/image-gallery' {
  declare module.exports: any;
}

declare module 'react-image-gallery/gulpfile' {
  declare module.exports: any;
}

declare module 'react-image-gallery/src/ImageGallery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-gallery/build/image-gallery.js' {
  declare module.exports: $Exports<'react-image-gallery/build/image-gallery'>;
}
declare module 'react-image-gallery/gulpfile.js' {
  declare module.exports: $Exports<'react-image-gallery/gulpfile'>;
}
declare module 'react-image-gallery/src/ImageGallery.jsx' {
  declare module.exports: $Exports<'react-image-gallery/src/ImageGallery'>;
}
