// flow-typed signature: 68b345cc632fbdc17443984a9e6ec222
// flow-typed version: <<STUB>>/react-app-rewire-mobx_v^1.0.8/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'react-app-rewire-mobx/index' {
  declare module.exports: $Exports<'react-app-rewire-mobx'>;
}
declare module 'react-app-rewire-mobx/index.js' {
  declare module.exports: $Exports<'react-app-rewire-mobx'>;
}
