// flow-typed signature: c82b7315e56c737bcc108b5bdf063bff
// flow-typed version: <<STUB>>/why-did-you-update_v^1.0.6/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'why-did-you-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'why-did-you-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'why-did-you-update/es/deepDiff' {
  declare module.exports: any;
}

declare module 'why-did-you-update/es/defaultNotifier' {
  declare module.exports: any;
}

declare module 'why-did-you-update/es/getDisplayName' {
  declare module.exports: any;
}

declare module 'why-did-you-update/es/index' {
  declare module.exports: any;
}

declare module 'why-did-you-update/es/normalizeOptions' {
  declare module.exports: any;
}

declare module 'why-did-you-update/es/shouldInclude' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/deepDiff' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/defaultNotifier' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/getDisplayName' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/index' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/normalizeOptions' {
  declare module.exports: any;
}

declare module 'why-did-you-update/lib/shouldInclude' {
  declare module.exports: any;
}

declare module 'why-did-you-update/umd/why-did-you-update' {
  declare module.exports: any;
}

declare module 'why-did-you-update/umd/why-did-you-update.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'why-did-you-update/es/deepDiff.js' {
  declare module.exports: $Exports<'why-did-you-update/es/deepDiff'>;
}
declare module 'why-did-you-update/es/defaultNotifier.js' {
  declare module.exports: $Exports<'why-did-you-update/es/defaultNotifier'>;
}
declare module 'why-did-you-update/es/getDisplayName.js' {
  declare module.exports: $Exports<'why-did-you-update/es/getDisplayName'>;
}
declare module 'why-did-you-update/es/index.js' {
  declare module.exports: $Exports<'why-did-you-update/es/index'>;
}
declare module 'why-did-you-update/es/normalizeOptions.js' {
  declare module.exports: $Exports<'why-did-you-update/es/normalizeOptions'>;
}
declare module 'why-did-you-update/es/shouldInclude.js' {
  declare module.exports: $Exports<'why-did-you-update/es/shouldInclude'>;
}
declare module 'why-did-you-update/lib/deepDiff.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/deepDiff'>;
}
declare module 'why-did-you-update/lib/defaultNotifier.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/defaultNotifier'>;
}
declare module 'why-did-you-update/lib/getDisplayName.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/getDisplayName'>;
}
declare module 'why-did-you-update/lib/index.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/index'>;
}
declare module 'why-did-you-update/lib/normalizeOptions.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/normalizeOptions'>;
}
declare module 'why-did-you-update/lib/shouldInclude.js' {
  declare module.exports: $Exports<'why-did-you-update/lib/shouldInclude'>;
}
declare module 'why-did-you-update/umd/why-did-you-update.js' {
  declare module.exports: $Exports<'why-did-you-update/umd/why-did-you-update'>;
}
declare module 'why-did-you-update/umd/why-did-you-update.min.js' {
  declare module.exports: $Exports<'why-did-you-update/umd/why-did-you-update.min'>;
}
