export default {
  typeSpaceNoSelect: '0',
  typeSpaceCloset: '1',
  typeSpaceRoom: '3',
  typeSpaceWarehouse: '4',
  typeSpaceOther: '5',
  typeReceiptNoSelect: '0',
  typeReceiptAll: '1',
  typeReceiptOnlyFTF: '2',
  typeReceiptOnlyDelivery: '3',
  statusVacancy: '0',
  statusNoVacancy: '1',
  statusConsultationRequired: '2',
  receiveAll: '1',
  receiveFaceToFace: '2',
  receiveDelivery: '3',
};
